name: Unix Sort Lite CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: |
            **/go.mod
      - name: Build
        run: |
          make build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5

      - name: Run Unit and Integration Tests
        run: |
          make test

      - name: Run Tests with Coverage
        run: |
          make test-cover

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          file: coverage.out
